export interface Country {
  countryCode: string;
  mobilePrefix: number | number[];
  emoji: string;
}

export type CountryType = {
  value: CountryCodeSet,
  mobilePrefix: number | number[];
  emoji: string;
}

export const countryCodeSet = {
  AD: "AD",
  AE: "AE",
  AF: "AF",
  AG: "AG",
  AI: "AI",
  AO: "AO",
  AR: "AR",
  AS: "AS",
  AT: "AT",
  AU: "AU",
  AW: "AW",
  AZ: "AZ",
  BA: "BA",
  BB: "BB",
  BD: "BD",
  BE: "BE",
  BF: "BF",
  BG: "BG",
  BH: "BH",
  BI: "BI",
  BJ: "BJ",
  BM: "BM",
  BN: "BN",
  BO: "BO",
  BQ: "BQ",
  BR: "BR",
  BS: "BS",
  BT: "BT",
  BW: "BW",
  BY: "BY",
  BZ: "BZ",
  CA: "CA",
  CC: "CC",
  CD: "CD",
  CF: "CF",
  CG: "CG",
  CH: "CH",
  CI: "CI",
  CK: "CK",
  CL: "CL",
  CM: "CM",
  CN: "CN",
  CO: "CO",
  CR: "CR",
  CU: "CU",
  CV: "CV",
  CW: "CW",
  CX: "CX",
  DE: "DE",
  DJ: "DJ",
  DK: "DK",
  DM: "DM",
  DO: "DO",
  EC: "EC",
  EE: "EE",
  EG: "EG",
  EH: "EH",
  ER: "ER",
  ES: "ES",
  ET: "ET",
  FI: "FI",
  FJ: "FJ",
  FK: "FK",
  FO: "FO",
  FR: "FR",
  GA: "GA",
  GD: "GD",
  GE: "GE",
  GF: "GF",
  GG: "GG",
  GH: "GH",
  GI: "GI",
  GL: "GL",
  GM: "GM",
  GN: "GN",
  GQ: "GQ",
  GR: "GR",
  GU: "GU",
  GW: "GW",
  GY: "GY",
  HK: "HK",
  HM: "HM",
  HT: "HT",
  HU: "HU",
  ID: "ID",
  IE: "IE",
  IL: "IL",
  IM: "IM",
  IN: "IN",
  IO: "IO",
  IS: "IS",
  IT: "IT",
  JE: "JE",
  JM: "JM",
  JO: "JO",
  JP: "JP",
  KE: "KE",
  KG: "KG",
  KH: "KH",
  KI: "KI",
  KP: "KP",
  KR: "KR",
  KW: "KW",
  KY: "KY",
  LA: "LA",
  LB: "LB",
  LC: "LC",
  LI: "LI",
  LK: "LK",
  LR: "LR",
  LS: "LS",
  LT: "LT",
  LU: "LU",
  LV: "LV",
  LY: "LY",
  MA: "MA",
  MC: "MC",
  MD: "MD",
  ME: "ME",
  MF: "MF",
  MG: "MG",
  MH: "MH",
  MK: "MK",
  ML: "ML",
  MM: "MM",
  MN: "MN",
  MO: "MO",
  MP: "MP",
  MQ: "MQ",
  MR: "MR",
  MS: "MS",
  MT: "MT",
  MU: "MU",
  MV: "MV",
  MW: "MW",
  MY: "MY",
  NA: "NA",
  NC: "NC",
  NE: "NE",
  NF: "NF",
  NG: "NG",
  NI: "NI",
  NL: "NL",
  NO: "NO",
  NP: "NP",
  NR: "NR",
  NU: "NU",
  OM: "OM",
  PA: "PA",
  PG: "PG",
  PH: "PH",
  PK: "PK",
  PM: "PM",
  PN: "PN",
  PR: "PR",
  PS: "PS",
  PT: "PT",
  PW: "PW",
  QA: "QA",
  RE: "RE",
  RO: "RO",
  RU: "RU",
  RW: "RW",
  SA: "SA",
  SB: "SB",
  SC: "SC",
  SD: "SD",
  SE: "SE",
  SG: "SG",
  SH: "SH",
  SI: "SI",
  SJ: "SJ",
  SK: "SK",
  SL: "SL",
  SM: "SM",
  SN: "SN",
  SO: "SO",
  SR: "SR",
  SS: "SS",
  ST: "ST",
  SV: "SV",
  SX: "SX",
  TC: "TC",
  TD: "TD",
  TF: "TF",
  TG: "TG",
  TH: "TH",
  TJ: "TJ",
  TK: "TK",
  TL: "TL",
  TM: "TM",
  TN: "TN",
  TO: "TO",
  TT: "TT",
  TV: "TV",
  TZ: "TZ",
  UA: "UA",
  UG: "UG",
  UM: "UM",
  US: "US",
  UY: "UY",
  UZ: "UZ",
  VA: "VA",
  VC: "VC",
  VE: "VE",
  VG: "VG",
  VI: "VI",
  VN: "VN",
  VU: "VU",
  WF: "WF",
  WS: "WS",
  YE: "YE",
  YT: "YT",
  ZM: "ZM",
  ZW: "ZW"
} as const;

export type CountryCodeSet = typeof countryCodeSet[keyof typeof countryCodeSet] | '';

export const CountryArr: readonly CountryType[] = [
  { value: countryCodeSet.AD, mobilePrefix: 376, emoji: "🇦🇩" },
  { value: countryCodeSet.AE, mobilePrefix: 971, emoji: "🇦🇪" },
  { value: countryCodeSet.AF, mobilePrefix: 93, emoji: "🇦🇫" },
  { value: countryCodeSet.AG, mobilePrefix: 1268, emoji: "🇦🇬" },
  { value: countryCodeSet.AI, mobilePrefix: 1264, emoji: "🇦🇮" },
  { value: countryCodeSet.AO, mobilePrefix: 244, emoji: "🇦🇴" },
  { value: countryCodeSet.AR, mobilePrefix: 54, emoji: "🇦🇷" },
  { value: countryCodeSet.AS, mobilePrefix: 1684, emoji: "🇦🇸" },
  { value: countryCodeSet.AT, mobilePrefix: 43, emoji: "🇦🇹" },
  { value: countryCodeSet.AU, mobilePrefix: 61, emoji: "🇦🇺" },
  { value: countryCodeSet.AW, mobilePrefix: 297, emoji: "🇦🇼" },
  { value: countryCodeSet.AZ, mobilePrefix: 994, emoji: "🇦🇿" },
  { value: countryCodeSet.BA, mobilePrefix: 387, emoji: "🇧🇦" },
  { value: countryCodeSet.BB, mobilePrefix: 1246, emoji: "🇧🇧" },
  { value: countryCodeSet.BD, mobilePrefix: 880, emoji: "🇧🇩" },
  { value: countryCodeSet.BE, mobilePrefix: 32, emoji: "🇧🇪" },
  { value: countryCodeSet.BF, mobilePrefix: 226, emoji: "🇧🇫" },
  { value: countryCodeSet.BG, mobilePrefix: 359, emoji: "🇧🇬" },
  { value: countryCodeSet.BH, mobilePrefix: 973, emoji: "🇧🇭" },
  { value: countryCodeSet.BI, mobilePrefix: 257, emoji: "🇧🇮" },
  { value: countryCodeSet.BJ, mobilePrefix: 229, emoji: "🇧🇯" },
  { value: countryCodeSet.BM, mobilePrefix: 1441, emoji: "🇧🇲" },
  { value: countryCodeSet.BN, mobilePrefix: 673, emoji: "🇧🇳" },
  { value: countryCodeSet.BO, mobilePrefix: 591, emoji: "🇧🇴" },
  { value: countryCodeSet.BQ, mobilePrefix: 599, emoji: "🇧🇶" },
  { value: countryCodeSet.BR, mobilePrefix: 55, emoji: "🇧🇷" },
  { value: countryCodeSet.BS, mobilePrefix: 1242, emoji: "🇧🇸" },
  { value: countryCodeSet.BT, mobilePrefix: 975, emoji: "🇧🇹" },
  { value: countryCodeSet.BW, mobilePrefix: 267, emoji: "🇧🇼" },
  { value: countryCodeSet.BY, mobilePrefix: 375, emoji: "🇧🇾" },
  { value: countryCodeSet.BZ, mobilePrefix: 501, emoji: "🇧🇿" },
  { value: countryCodeSet.CA, mobilePrefix: 1, emoji: "🇨🇦" },
  { value: countryCodeSet.CC, mobilePrefix: 61, emoji: "🇨🇨" },
  { value: countryCodeSet.CD, mobilePrefix: 243, emoji: "🇨🇩" },
  { value: countryCodeSet.CF, mobilePrefix: 236, emoji: "🇨🇫" },
  { value: countryCodeSet.CG, mobilePrefix: 242, emoji: "🇨🇬" },
  { value: countryCodeSet.CH, mobilePrefix: 41, emoji: "🇨🇭" },
  { value: countryCodeSet.CI, mobilePrefix: 225, emoji: "🇨🇮" },
  { value: countryCodeSet.CK, mobilePrefix: 682, emoji: "🇨🇰" },
  { value: countryCodeSet.CL, mobilePrefix: 56, emoji: "🇨🇱" },
  { value: countryCodeSet.CM, mobilePrefix: 237, emoji: "🇨🇲" },
  { value: countryCodeSet.CN, mobilePrefix: 86, emoji: "🇨🇳" },
  { value: countryCodeSet.CO, mobilePrefix: 57, emoji: "🇨🇴" },
  { value: countryCodeSet.CR, mobilePrefix: 506, emoji: "🇨🇷" },
  { value: countryCodeSet.CU, mobilePrefix: 53, emoji: "🇨🇺" },
  { value: countryCodeSet.CV, mobilePrefix: 238, emoji: "🇨🇻" },
  { value: countryCodeSet.CW, mobilePrefix: 599, emoji: "🇨🇼" },
  { value: countryCodeSet.CX, mobilePrefix: 61, emoji: "🇨🇽" },
  { value: countryCodeSet.DE, mobilePrefix: 49, emoji: "🇩🇪" },
  { value: countryCodeSet.DJ, mobilePrefix: 253, emoji: "🇩🇯" },
  { value: countryCodeSet.DK, mobilePrefix: 45, emoji: "🇩🇰" },
  { value: countryCodeSet.DM, mobilePrefix: 1767, emoji: "🇩🇲" },
  { value: countryCodeSet.DO, mobilePrefix: [1809, 1829, 1849], emoji: "🇩🇴" },
  { value: countryCodeSet.EC, mobilePrefix: 593, emoji: "🇪🇨" },
  { value: countryCodeSet.EE, mobilePrefix: 372, emoji: "🇪🇪" },
  { value: countryCodeSet.EG, mobilePrefix: 20, emoji: "🇪🇬" },
  { value: countryCodeSet.EH, mobilePrefix: 212, emoji: "🇪🇭" },
  { value: countryCodeSet.ER, mobilePrefix: 291, emoji: "🇪🇷" },
  { value: countryCodeSet.ES, mobilePrefix: 34, emoji: "🇪🇸" },
  { value: countryCodeSet.ET, mobilePrefix: 251, emoji: "🇪🇹" },
  { value: countryCodeSet.FI, mobilePrefix: 358, emoji: "🇫🇮" },
  { value: countryCodeSet.FJ, mobilePrefix: 679, emoji: "🇫🇯" },
  { value: countryCodeSet.FK, mobilePrefix: 500, emoji: "🇫🇰" },
  { value: countryCodeSet.FO, mobilePrefix: 298, emoji: "🇫🇴" },
  { value: countryCodeSet.FR, mobilePrefix: 33, emoji: "🇫🇷" },
  { value: countryCodeSet.GA, mobilePrefix: 241, emoji: "🇬🇦" },
  { value: countryCodeSet.GD, mobilePrefix: 1473, emoji: "🇬🇩" },
  { value: countryCodeSet.GE, mobilePrefix: 995, emoji: "🇬🇪" },
  { value: countryCodeSet.GF, mobilePrefix: 594, emoji: "🇬🇫" },
  { value: countryCodeSet.GG, mobilePrefix: 44, emoji: "🇬🇬" },
  { value: countryCodeSet.GH, mobilePrefix: 233, emoji: "🇬🇭" },
  { value: countryCodeSet.GI, mobilePrefix: 350, emoji: "🇬🇮" },
  { value: countryCodeSet.GL, mobilePrefix: 299, emoji: "🇬🇱" },
  { value: countryCodeSet.GM, mobilePrefix: 220, emoji: "🇬🇲" },
  { value: countryCodeSet.GN, mobilePrefix: 224, emoji: "🇬🇳" },
  { value: countryCodeSet.GQ, mobilePrefix: 240, emoji: "🇬🇶" },
  { value: countryCodeSet.GR, mobilePrefix: 30, emoji: "🇬🇷" },
  { value: countryCodeSet.GU, mobilePrefix: 1671, emoji: "🇬🇺" },
  { value: countryCodeSet.GW, mobilePrefix: 245, emoji: "🇬🇼" },
  { value: countryCodeSet.GY, mobilePrefix: 592, emoji: "🇬🇾" },
  { value: countryCodeSet.HK, mobilePrefix: 852, emoji: "🇭🇰" },
  { value: countryCodeSet.HM, mobilePrefix: 672, emoji: "🇭🇲" },
  { value: countryCodeSet.HT, mobilePrefix: 509, emoji: "🇭🇹" },
  { value: countryCodeSet.HU, mobilePrefix: 36, emoji: "🇭🇺" },
  { value: countryCodeSet.ID, mobilePrefix: 62, emoji: "🇮🇩" },
  { value: countryCodeSet.IE, mobilePrefix: 353, emoji: "🇮🇪" },
  { value: countryCodeSet.IL, mobilePrefix: 972, emoji: "🇮🇱" },
  { value: countryCodeSet.IM, mobilePrefix: 44, emoji: "🇮🇲" },
  { value: countryCodeSet.IN, mobilePrefix: 91, emoji: "🇮🇳" },
  { value: countryCodeSet.IO, mobilePrefix: 246, emoji: "🇮🇴" },
  { value: countryCodeSet.IS, mobilePrefix: 354, emoji: "🇮🇸" },
  { value: countryCodeSet.IT, mobilePrefix: 39, emoji: "🇮🇹" },
  { value: countryCodeSet.JE, mobilePrefix: 44, emoji: "🇯🇪" },
  { value: countryCodeSet.JM, mobilePrefix: 1876, emoji: "🇯🇲" },
  { value: countryCodeSet.JO, mobilePrefix: 962, emoji: "🇯🇴" },
  { value: countryCodeSet.JP, mobilePrefix: 81, emoji: "🇯🇵" },
  { value: countryCodeSet.KE, mobilePrefix: 254, emoji: "🇰🇪" },
  { value: countryCodeSet.KG, mobilePrefix: 996, emoji: "🇰🇬" },
  { value: countryCodeSet.KH, mobilePrefix: 855, emoji: "🇰🇭" },
  { value: countryCodeSet.KI, mobilePrefix: 686, emoji: "🇰🇮" },
  { value: countryCodeSet.KP, mobilePrefix: 850, emoji: "🇰🇵" },
  { value: countryCodeSet.KR, mobilePrefix: 82, emoji: "🇰🇷" },
  { value: countryCodeSet.KW, mobilePrefix: 965, emoji: "🇰🇼" },
  { value: countryCodeSet.KY, mobilePrefix: 1345, emoji: "🇰🇾" },
  { value: countryCodeSet.LA, mobilePrefix: 856, emoji: "🇱🇦" },
  { value: countryCodeSet.LB, mobilePrefix: 961, emoji: "🇱🇧" },
  { value: countryCodeSet.LC, mobilePrefix: 1758, emoji: "🇱🇨" },
  { value: countryCodeSet.LI, mobilePrefix: 423, emoji: "🇱🇮" },
  { value: countryCodeSet.LK, mobilePrefix: 94, emoji: "🇱🇰" },
  { value: countryCodeSet.LR, mobilePrefix: 231, emoji: "🇱🇷" },
  { value: countryCodeSet.LS, mobilePrefix: 266, emoji: "🇱🇸" },
  { value: countryCodeSet.LT, mobilePrefix: 370, emoji: "🇱🇹" },
  { value: countryCodeSet.LU, mobilePrefix: 352, emoji: "🇱🇺" },
  { value: countryCodeSet.LV, mobilePrefix: 371, emoji: "🇱🇻" },
  { value: countryCodeSet.LY, mobilePrefix: 218, emoji: "🇱🇾" },
  { value: countryCodeSet.MA, mobilePrefix: 212, emoji: "🇲🇦" },
  { value: countryCodeSet.MC, mobilePrefix: 377, emoji: "🇲🇨" },
  { value: countryCodeSet.MD, mobilePrefix: 373, emoji: "🇲🇩" },
  { value: countryCodeSet.ME, mobilePrefix: 382, emoji: "🇲🇪" },
  { value: countryCodeSet.MF, mobilePrefix: 590, emoji: "🇲🇫" },
  { value: countryCodeSet.MG, mobilePrefix: 261, emoji: "🇲🇬" },
  { value: countryCodeSet.MH, mobilePrefix: 692, emoji: "🇲🇭" },
  { value: countryCodeSet.MK, mobilePrefix: 389, emoji: "🇲🇰" },
  { value: countryCodeSet.ML, mobilePrefix: 223, emoji: "🇲🇱" },
  { value: countryCodeSet.MM, mobilePrefix: 95, emoji: "🇲🇲" },
  { value: countryCodeSet.MN, mobilePrefix: 976, emoji: "🇲🇳" },
  { value: countryCodeSet.MO, mobilePrefix: 853, emoji: "🇲🇴" },
  { value: countryCodeSet.MP, mobilePrefix: 1670, emoji: "🇲🇵" },
  { value: countryCodeSet.MQ, mobilePrefix: 596, emoji: "🇲🇶" },
  { value: countryCodeSet.MR, mobilePrefix: 222, emoji: "🇲🇷" },
  { value: countryCodeSet.MS, mobilePrefix: 1664, emoji: "🇲🇸" },
  { value: countryCodeSet.MT, mobilePrefix: 356, emoji: "🇲🇹" },
  { value: countryCodeSet.MU, mobilePrefix: 230, emoji: "🇲🇺" },
  { value: countryCodeSet.MV, mobilePrefix: 960, emoji: "🇲🇻" },
  { value: countryCodeSet.MW, mobilePrefix: 265, emoji: "🇲🇼" },
  { value: countryCodeSet.MY, mobilePrefix: 60, emoji: "🇲🇾" },
  { value: countryCodeSet.NA, mobilePrefix: 264, emoji: "🇳🇦" },
  { value: countryCodeSet.NC, mobilePrefix: 687, emoji: "🇳🇨" },
  { value: countryCodeSet.NE, mobilePrefix: 227, emoji: "🇳🇪" },
  { value: countryCodeSet.NF, mobilePrefix: 672, emoji: "🇳🇫" },
  { value: countryCodeSet.NG, mobilePrefix: 234, emoji: "🇳🇬" },
  { value: countryCodeSet.NI, mobilePrefix: 505, emoji: "🇳🇮" },
  { value: countryCodeSet.NL, mobilePrefix: 31, emoji: "🇳🇱" },
  { value: countryCodeSet.NO, mobilePrefix: 47, emoji: "🇳🇴" },
  { value: countryCodeSet.NP, mobilePrefix: 977, emoji: "🇳🇵" },
  { value: countryCodeSet.NR, mobilePrefix: 674, emoji: "🇳🇷" },
  { value: countryCodeSet.NU, mobilePrefix: 683, emoji: "🇳🇺" },
  { value: countryCodeSet.OM, mobilePrefix: 968, emoji: "🇴🇲" },
  { value: countryCodeSet.PA, mobilePrefix: 507, emoji: "🇵🇦" },
  { value: countryCodeSet.PG, mobilePrefix: 675, emoji: "🇵🇬" },
  { value: countryCodeSet.PH, mobilePrefix: 63, emoji: "🇵🇭" },
  { value: countryCodeSet.PK, mobilePrefix: 92, emoji: "🇵🇰" },
  { value: countryCodeSet.PM, mobilePrefix: 508, emoji: "🇵🇲" },
  { value: countryCodeSet.PN, mobilePrefix: 872, emoji: "🇵🇳" },
  { value: countryCodeSet.PR, mobilePrefix: 1, emoji: "🇵🇷" },
  { value: countryCodeSet.PS, mobilePrefix: 970, emoji: "🇵🇸" },
  { value: countryCodeSet.PT, mobilePrefix: 351, emoji: "🇵🇹" },
  { value: countryCodeSet.PW, mobilePrefix: 680, emoji: "🇵🇼" },
  { value: countryCodeSet.QA, mobilePrefix: 974, emoji: "🇶🇦" },
  { value: countryCodeSet.RE, mobilePrefix: 262, emoji: "🇷🇪" },
  { value: countryCodeSet.RO, mobilePrefix: 40, emoji: "🇷🇴" },
  { value: countryCodeSet.RU, mobilePrefix: 7, emoji: "🇷🇺" },
  { value: countryCodeSet.RW, mobilePrefix: 250, emoji: "🇷🇼" },
  { value: countryCodeSet.SA, mobilePrefix: 966, emoji: "🇸🇦" },
  { value: countryCodeSet.SB, mobilePrefix: 677, emoji: "🇸🇧" },
  { value: countryCodeSet.SC, mobilePrefix: 248, emoji: "🇸🇨" },
  { value: countryCodeSet.SD, mobilePrefix: 249, emoji: "🇸🇩" },
  { value: countryCodeSet.SE, mobilePrefix: 46, emoji: "🇸🇪" },
  { value: countryCodeSet.SG, mobilePrefix: 65, emoji: "🇸🇬" },
  { value: countryCodeSet.SH, mobilePrefix: 290, emoji: "🇸🇭" },
  { value: countryCodeSet.SI, mobilePrefix: 386, emoji: "🇸🇮" },
  { value: countryCodeSet.SJ, mobilePrefix: 47, emoji: "🇸🇯" },
  { value: countryCodeSet.SK, mobilePrefix: 421, emoji: "🇸🇰" },
  { value: countryCodeSet.SL, mobilePrefix: 232, emoji: "🇸🇱" },
  { value: countryCodeSet.SM, mobilePrefix: 378, emoji: "🇸🇲" },
  { value: countryCodeSet.SN, mobilePrefix: 221, emoji: "🇸🇳" },
  { value: countryCodeSet.SO, mobilePrefix: 252, emoji: "🇸🇴" },
  { value: countryCodeSet.SR, mobilePrefix: 597, emoji: "🇸🇷" },
  { value: countryCodeSet.SS, mobilePrefix: 211, emoji: "🇸🇸" },
  { value: countryCodeSet.ST, mobilePrefix: 239, emoji: "🇸🇹" },
  { value: countryCodeSet.SV, mobilePrefix: 503, emoji: "🇸🇻" },
  { value: countryCodeSet.SX, mobilePrefix: 599, emoji: "🇸🇽" },
  { value: countryCodeSet.TC, mobilePrefix: 1649, emoji: "🇹🇨" },
  { value: countryCodeSet.TD, mobilePrefix: 235, emoji: "🇹🇩" },
  { value: countryCodeSet.TF, mobilePrefix: 262, emoji: "🇹🇫" },
  { value: countryCodeSet.TG, mobilePrefix: 228, emoji: "🇹🇬" },
  { value: countryCodeSet.TH, mobilePrefix: 66, emoji: "🇹🇭" },
  { value: countryCodeSet.TJ, mobilePrefix: 992, emoji: "🇹🇯" },
  { value: countryCodeSet.TK, mobilePrefix: 690, emoji: "🇹🇰" },
  { value: countryCodeSet.TL, mobilePrefix: 670, emoji: "🇹🇱" },
  { value: countryCodeSet.TM, mobilePrefix: 993, emoji: "🇹🇲" },
  { value: countryCodeSet.TN, mobilePrefix: 216, emoji: "🇹🇳" },
  { value: countryCodeSet.TO, mobilePrefix: 676, emoji: "🇹🇴" },
  { value: countryCodeSet.TT, mobilePrefix: 1868, emoji: "🇹🇹" },
  { value: countryCodeSet.TV, mobilePrefix: 688, emoji: "🇹🇻" },
  { value: countryCodeSet.TZ, mobilePrefix: 255, emoji: "🇹🇿" },
  { value: countryCodeSet.UA, mobilePrefix: 380, emoji: "🇺🇦" },
  { value: countryCodeSet.UG, mobilePrefix: 256, emoji: "🇺🇬" },
  { value: countryCodeSet.UM, mobilePrefix: 1, emoji: "🇺🇲" },
  { value: countryCodeSet.US, mobilePrefix: 1, emoji: "🇺🇸" },
  { value: countryCodeSet.UY, mobilePrefix: 598, emoji: "🇺🇾" },
  { value: countryCodeSet.UZ, mobilePrefix: 998, emoji: "🇺🇿" },
  { value: countryCodeSet.VA, mobilePrefix: 39, emoji: "🇻🇦" },
  { value: countryCodeSet.VC, mobilePrefix: 1784, emoji: "🇻🇨" },
  { value: countryCodeSet.VE, mobilePrefix: 58, emoji: "🇻🇪" },
  { value: countryCodeSet.VG, mobilePrefix: 1284, emoji: "🇻🇬" },
  { value: countryCodeSet.VI, mobilePrefix: 1340, emoji: "🇻🇮" },
  { value: countryCodeSet.VN, mobilePrefix: 84, emoji: "🇻🇳" },
  { value: countryCodeSet.VU, mobilePrefix: 678, emoji: "🇻🇺" },
  { value: countryCodeSet.WF, mobilePrefix: 681, emoji: "🇼🇫" },
  { value: countryCodeSet.WS, mobilePrefix: 685, emoji: "🇼🇸" },
  { value: countryCodeSet.YE, mobilePrefix: 967, emoji: "🇾🇪" },
  { value: countryCodeSet.YT, mobilePrefix: 262, emoji: "🇾🇹" },
  { value: countryCodeSet.ZM, mobilePrefix: 260, emoji: "🇿🇲" },
  { value: countryCodeSet.ZW, mobilePrefix: 263, emoji: "🇿🇼" }
];

export const CountryMap = new Map<CountryCodeSet, CountryType>(CountryArr.map(item => [item.value, item]));

// 修复IS的错误属性名称
export const getCountryArr = () => CountryArr;

export const i18nCountry = {
  zh_CN: {
    'kysion.country.name.AD': '安道尔',
    'kysion.country.name.AE': '阿联酋',
    'kysion.country.name.AF': '阿富汗',
    'kysion.country.name.AG': '安提瓜和巴布达',
    'kysion.country.name.AI': '安圭拉',
    'kysion.country.name.AO': '安哥拉',
    'kysion.country.name.AR': '阿根廷',
    'kysion.country.name.AS': '美属萨摩亚',
    'kysion.country.name.AT': '奥地利',
    'kysion.country.name.AU': '澳大利亚',
    'kysion.country.name.AW': '阿鲁巴',
    'kysion.country.name.AZ': '阿塞拜疆',
    'kysion.country.name.BA': '波黑',
    'kysion.country.name.BB': '巴巴多斯',
    'kysion.country.name.BD': '孟加拉国',
    'kysion.country.name.BE': '比利时',
    'kysion.country.name.BF': '布基纳法索',
    'kysion.country.name.BG': '保加利亚',
    'kysion.country.name.BH': '巴林',
    'kysion.country.name.BI': '布隆迪',
    'kysion.country.name.BJ': '贝宁',
    'kysion.country.name.BM': '百慕大',
    'kysion.country.name.BN': '文莱',
    'kysion.country.name.BO': '玻利维亚',
    'kysion.country.name.BQ': '荷兰加勒比区',
    'kysion.country.name.BR': '巴西',
    'kysion.country.name.BS': '巴哈马',
    'kysion.country.name.BT': '不丹',
    'kysion.country.name.BW': '博茨瓦纳',
    'kysion.country.name.BY': '白俄罗斯',
    'kysion.country.name.BZ': '伯利兹',
    'kysion.country.name.CA': '加拿大',
    'kysion.country.name.CC': '科科斯群岛',
    'kysion.country.name.CD': '刚果民主共和国',
    'kysion.country.name.CF': '中非共和国',
    'kysion.country.name.CG': '刚果共和国',
    'kysion.country.name.CH': '瑞士',
    'kysion.country.name.CI': '科特迪瓦',
    'kysion.country.name.CK': '库克群岛',
    'kysion.country.name.CL': '智利',
    'kysion.country.name.CM': '喀麦隆',
    'kysion.country.name.CN': '中国',
    'kysion.country.name.CO': '哥伦比亚',
    'kysion.country.name.CR': '哥斯达黎加',
    'kysion.country.name.CU': '古巴',
    'kysion.country.name.CV': '佛得角',
    'kysion.country.name.CW': '库拉索',
    'kysion.country.name.CX': '圣诞岛',
    'kysion.country.name.DE': '德国',
    'kysion.country.name.DJ': '吉布提',
    'kysion.country.name.DK': '丹麦',
    'kysion.country.name.DM': '多米尼克',
    'kysion.country.name.DO': '多米尼加共和国',
    'kysion.country.name.EC': '厄瓜多尔',
    'kysion.country.name.EE': '爱沙尼亚',
    'kysion.country.name.EG': '埃及',
    'kysion.country.name.EH': '西撒哈拉',
    'kysion.country.name.ER': '厄立特里亚',
    'kysion.country.name.ES': '西班牙',
    'kysion.country.name.ET': '埃塞俄比亚',
    'kysion.country.name.FI': '芬兰',
    'kysion.country.name.FJ': '斐济',
    'kysion.country.name.FK': '福克兰群岛',
    'kysion.country.name.FO': '法罗群岛',
    'kysion.country.name.FR': '法国',
    'kysion.country.name.GA': '加蓬',
    'kysion.country.name.GD': '格林纳达',
    'kysion.country.name.GE': '格鲁吉亚',
    'kysion.country.name.GF': '法属圭亚那',
    'kysion.country.name.GG': '根西岛',
    'kysion.country.name.GH': '加纳',
    'kysion.country.name.GI': '直布罗陀',
    'kysion.country.name.GL': '格陵兰',
    'kysion.country.name.GM': '冈比亚',
    'kysion.country.name.GN': '几内亚',
    'kysion.country.name.GQ': '赤道几内亚',
    'kysion.country.name.GR': '希腊',
    'kysion.country.name.GU': '关岛',
    'kysion.country.name.GW': '几内亚比绍',
    'kysion.country.name.GY': '圭亚那',
    'kysion.country.name.HK': '香港',
    'kysion.country.name.HM': '赫德岛和麦克唐纳群岛',
    'kysion.country.name.HT': '海地',
    'kysion.country.name.HU': '匈牙利',
    'kysion.country.name.ID': '印度尼西亚',
    'kysion.country.name.IE': '爱尔兰',
    'kysion.country.name.IL': '以色列',
    'kysion.country.name.IM': '马恩岛',
    'kysion.country.name.IN': '印度',
    'kysion.country.name.IO': '英属印度洋领地',
    'kysion.country.name.IS': '冰岛',
    'kysion.country.name.IT': '意大利',
    'kysion.country.name.JE': '泽西岛',
    'kysion.country.name.JM': '牙买加',
    'kysion.country.name.JO': '约旦',
    'kysion.country.name.JP': '日本',
    'kysion.country.name.KE': '肯尼亚',
    'kysion.country.name.KG': '吉尔吉斯斯坦',
    'kysion.country.name.KH': '柬埔寨',
    'kysion.country.name.KI': '基里巴斯',
    'kysion.country.name.KP': '朝鲜',
    'kysion.country.name.KR': '韩国',
    'kysion.country.name.KW': '科威特',
    'kysion.country.name.KY': '开曼群岛',
    'kysion.country.name.LA': '老挝',
    'kysion.country.name.LB': '黎巴嫩',
    'kysion.country.name.LC': '圣卢西亚',
    'kysion.country.name.LI': '列支敦士登',
    'kysion.country.name.LK': '斯里兰卡',
    'kysion.country.name.LR': '利比里亚',
    'kysion.country.name.LS': '莱索托',
    'kysion.country.name.LT': '立陶宛',
    'kysion.country.name.LU': '卢森堡',
    'kysion.country.name.LV': '拉脱维亚',
    'kysion.country.name.LY': '利比亚',
    'kysion.country.name.MA': '摩洛哥',
    'kysion.country.name.MC': '摩纳哥',
    'kysion.country.name.MD': '摩尔多瓦',
    'kysion.country.name.ME': '黑山',
    'kysion.country.name.MF': '法属圣马丁',
    'kysion.country.name.MG': '马达加斯加',
    'kysion.country.name.MH': '马绍尔群岛',
    'kysion.country.name.MK': '北马其顿',
    'kysion.country.name.ML': '马里',
    'kysion.country.name.MM': '缅甸',
    'kysion.country.name.MN': '蒙古',
    'kysion.country.name.MO': '澳门',
    'kysion.country.name.MP': '北马里亚纳群岛',
    'kysion.country.name.MQ': '马提尼克',
    'kysion.country.name.MR': '毛里塔尼亚',
    'kysion.country.name.MS': '蒙特塞拉特',
    'kysion.country.name.MT': '马耳他',
    'kysion.country.name.MU': '毛里求斯',
    'kysion.country.name.MV': '马尔代夫',
    'kysion.country.name.MW': '马拉维',
    'kysion.country.name.MY': '马来西亚',
    'kysion.country.name.NA': '纳米比亚',
    'kysion.country.name.NC': '新喀里多尼亚',
    'kysion.country.name.NE': '尼日尔',
    'kysion.country.name.NF': '诺福克岛',
    'kysion.country.name.NG': '尼日利亚',
    'kysion.country.name.NI': '尼加拉瓜',
    'kysion.country.name.NL': '荷兰',
    'kysion.country.name.NO': '挪威',
    'kysion.country.name.NP': '尼泊尔',
    'kysion.country.name.NR': '瑙鲁',
    'kysion.country.name.NU': '纽埃',
    'kysion.country.name.OM': '阿曼',
    'kysion.country.name.PA': '巴拿马',
    'kysion.country.name.PG': '巴布亚新几内亚',
    'kysion.country.name.PH': '菲律宾',
    'kysion.country.name.PK': '巴基斯坦',
    'kysion.country.name.PM': '圣皮埃尔和密克隆',
    'kysion.country.name.PN': '皮特凯恩群岛',
    'kysion.country.name.PR': '波多黎各',
    'kysion.country.name.PS': '巴勒斯坦',
    'kysion.country.name.PT': '葡萄牙',
    'kysion.country.name.PW': '帕劳',
    'kysion.country.name.QA': '卡塔尔',
    'kysion.country.name.RE': '留尼汪',
    'kysion.country.name.RO': '罗马尼亚',
    'kysion.country.name.RU': '俄罗斯',
    'kysion.country.name.RW': '卢旺达',
    'kysion.country.name.SA': '沙特阿拉伯',
    'kysion.country.name.SB': '所罗门群岛',
    'kysion.country.name.SC': '塞舌尔',
    'kysion.country.name.SD': '苏丹',
    'kysion.country.name.SE': '瑞典',
    'kysion.country.name.SG': '新加坡',
    'kysion.country.name.SH': '圣赫勒拿',
    'kysion.country.name.SI': '斯洛文尼亚',
    'kysion.country.name.SJ': '斯瓦尔巴群岛和扬马延岛',
    'kysion.country.name.SK': '斯洛伐克',
    'kysion.country.name.SL': '塞拉利昂',
    'kysion.country.name.SM': '圣马力诺',
    'kysion.country.name.SN': '塞内加尔',
    'kysion.country.name.SO': '索马里',
    'kysion.country.name.SR': '苏里南',
    'kysion.country.name.SS': '南苏丹',
    'kysion.country.name.ST': '圣多美和普林西比',
    'kysion.country.name.SV': '萨尔瓦多',
    'kysion.country.name.SX': '荷属圣马丁',
    'kysion.country.name.TC': '特克斯和凯科斯群岛',
    'kysion.country.name.TD': '乍得',
    'kysion.country.name.TF': '法属南部领地',
    'kysion.country.name.TG': '多哥',
    'kysion.country.name.TH': '泰国',
    'kysion.country.name.TJ': '塔吉克斯坦',
    'kysion.country.name.TK': '托克劳',
    'kysion.country.name.TL': '东帝汶',
    'kysion.country.name.TM': '土库曼斯坦',
    'kysion.country.name.TN': '突尼斯',
    'kysion.country.name.TO': '汤加',
    'kysion.country.name.TT': '特立尼达和多巴哥',
    'kysion.country.name.TV': '图瓦卢',
    'kysion.country.name.TZ': '坦桑尼亚',
    'kysion.country.name.UA': '乌克兰',
    'kysion.country.name.UG': '乌干达',
    'kysion.country.name.UM': '美国本土外小岛屿',
    'kysion.country.name.US': '美国',
    'kysion.country.name.UY': '乌拉圭',
    'kysion.country.name.UZ': '乌兹别克斯坦',
    'kysion.country.name.VA': '梵蒂冈',
    'kysion.country.name.VC': '圣文森特和格林纳丁斯',
    'kysion.country.name.VE': '委内瑞拉',
    'kysion.country.name.VG': '英属维尔京群岛',
    'kysion.country.name.VI': '美属维尔京群岛',
    'kysion.country.name.VN': '越南',
    'kysion.country.name.VU': '瓦努阿图',
    'kysion.country.name.WF': '瓦利斯和富图纳',
    'kysion.country.name.WS': '萨摩亚',
    'kysion.country.name.YE': '也门',
    'kysion.country.name.YT': '马约特',
    'kysion.country.name.ZM': '赞比亚',
    'kysion.country.name.ZW': '津巴布韦'
  },
  en_US: {
    'kysion.country.name.AD': 'Andorra',
    'kysion.country.name.AE': 'United Arab Emirates',
    'kysion.country.name.AF': 'Afghanistan',
    'kysion.country.name.AG': 'Antigua and Barbuda',
    'kysion.country.name.AI': 'Anguilla',
    'kysion.country.name.AO': 'Angola',
    'kysion.country.name.AR': 'Argentina',
    'kysion.country.name.AS': 'American Samoa',
    'kysion.country.name.AT': 'Austria',
    'kysion.country.name.AU': 'Australia',
    'kysion.country.name.AW': 'Aruba',
    'kysion.country.name.AZ': 'Azerbaijan',
    'kysion.country.name.BA': 'Bosnia and Herzegovina',
    'kysion.country.name.BB': 'Barbados',
    'kysion.country.name.BD': 'Bangladesh',
    'kysion.country.name.BE': 'Belgium',
    'kysion.country.name.BF': 'Burkina Faso',
    'kysion.country.name.BG': 'Bulgaria',
    'kysion.country.name.BH': 'Bahrain',
    'kysion.country.name.BI': 'Burundi',
    'kysion.country.name.BJ': 'Benin',
    'kysion.country.name.BM': 'Bermuda',
    'kysion.country.name.BN': 'Brunei',
    'kysion.country.name.BO': 'Bolivia',
    'kysion.country.name.BQ': 'Caribbean Netherlands',
    'kysion.country.name.BR': 'Brazil',
    'kysion.country.name.BS': 'Bahamas',
    'kysion.country.name.BT': 'Bhutan',
    'kysion.country.name.BW': 'Botswana',
    'kysion.country.name.BY': 'Belarus',
    'kysion.country.name.BZ': 'Belize',
    'kysion.country.name.CA': 'Canada',
    'kysion.country.name.CC': 'Cocos Islands',
    'kysion.country.name.CD': 'Democratic Republic of the Congo',
    'kysion.country.name.CF': 'Central African Republic',
    'kysion.country.name.CG': 'Republic of the Congo',
    'kysion.country.name.CH': 'Switzerland',
    'kysion.country.name.CI': 'Ivory Coast',
    'kysion.country.name.CK': 'Cook Islands',
    'kysion.country.name.CL': 'Chile',
    'kysion.country.name.CM': 'Cameroon',
    'kysion.country.name.CN': 'China',
    'kysion.country.name.CO': 'Colombia',
    'kysion.country.name.CR': 'Costa Rica',
    'kysion.country.name.CU': 'Cuba',
    'kysion.country.name.CV': 'Cape Verde',
    'kysion.country.name.CW': 'Curaçao',
    'kysion.country.name.CX': 'Christmas Island',
    'kysion.country.name.DE': 'Germany',
    'kysion.country.name.DJ': 'Djibouti',
    'kysion.country.name.DK': 'Denmark',
    'kysion.country.name.DM': 'Dominica',
    'kysion.country.name.DO': 'Dominican Republic',
    'kysion.country.name.EC': 'Ecuador',
    'kysion.country.name.EE': 'Estonia',
    'kysion.country.name.EG': 'Egypt',
    'kysion.country.name.EH': 'Western Sahara',
    'kysion.country.name.ER': 'Eritrea',
    'kysion.country.name.ES': 'Spain',
    'kysion.country.name.ET': 'Ethiopia',
    'kysion.country.name.FI': 'Finland',
    'kysion.country.name.FJ': 'Fiji',
    'kysion.country.name.FK': 'Falkland Islands',
    'kysion.country.name.FO': 'Faroe Islands',
    'kysion.country.name.FR': 'France',
    'kysion.country.name.GA': 'Gabon',
    'kysion.country.name.GD': 'Grenada',
    'kysion.country.name.GE': 'Georgia',
    'kysion.country.name.GF': 'French Guiana',
    'kysion.country.name.GG': 'Guernsey',
    'kysion.country.name.GH': 'Ghana',
    'kysion.country.name.GI': 'Gibraltar',
    'kysion.country.name.GL': 'Greenland',
    'kysion.country.name.GM': 'Gambia',
    'kysion.country.name.GN': 'Guinea',
    'kysion.country.name.GQ': 'Equatorial Guinea',
    'kysion.country.name.GR': 'Greece',
    'kysion.country.name.GU': 'Guam',
    'kysion.country.name.GW': 'Guinea-Bissau',
    'kysion.country.name.GY': 'Guyana',
    'kysion.country.name.HK': 'Hong Kong',
    'kysion.country.name.HM': 'Heard Island and McDonald Islands',
    'kysion.country.name.HT': 'Haiti',
    'kysion.country.name.HU': 'Hungary',
    'kysion.country.name.ID': 'Indonesia',
    'kysion.country.name.IE': 'Ireland',
    'kysion.country.name.IL': 'Israel',
    'kysion.country.name.IM': 'Isle of Man',
    'kysion.country.name.IN': 'India',
    'kysion.country.name.IO': 'British Indian Ocean Territory',
    'kysion.country.name.IS': 'Iceland',
    'kysion.country.name.IT': 'Italy',
    'kysion.country.name.JE': 'Jersey',
    'kysion.country.name.JM': 'Jamaica',
    'kysion.country.name.JO': 'Jordan',
    'kysion.country.name.JP': 'Japan',
    'kysion.country.name.KE': 'Kenya',
    'kysion.country.name.KG': 'Kyrgyzstan',
    'kysion.country.name.KH': 'Cambodia',
    'kysion.country.name.KI': 'Kiribati',
    'kysion.country.name.KP': 'North Korea',
    'kysion.country.name.KR': 'South Korea',
    'kysion.country.name.KW': 'Kuwait',
    'kysion.country.name.KY': 'Cayman Islands',
    'kysion.country.name.LA': 'Laos',
    'kysion.country.name.LB': 'Lebanon',
    'kysion.country.name.LC': 'Saint Lucia',
    'kysion.country.name.LI': 'Liechtenstein',
    'kysion.country.name.LK': 'Sri Lanka',
    'kysion.country.name.LR': 'Liberia',
    'kysion.country.name.LS': 'Lesotho',
    'kysion.country.name.LT': 'Lithuania',
    'kysion.country.name.LU': 'Luxembourg',
    'kysion.country.name.LV': 'Latvia',
    'kysion.country.name.LY': 'Libya',
    'kysion.country.name.MA': 'Morocco',
    'kysion.country.name.MC': 'Monaco',
    'kysion.country.name.MD': 'Moldova',
    'kysion.country.name.ME': 'Montenegro',
    'kysion.country.name.MF': 'Saint Martin',
    'kysion.country.name.MG': 'Madagascar',
    'kysion.country.name.MH': 'Marshall Islands',
    'kysion.country.name.MK': 'North Macedonia',
    'kysion.country.name.ML': 'Mali',
    'kysion.country.name.MM': 'Myanmar',
    'kysion.country.name.MN': 'Mongolia',
    'kysion.country.name.MO': 'Macau',
    'kysion.country.name.MP': 'Northern Mariana Islands',
    'kysion.country.name.MQ': 'Martinique',
    'kysion.country.name.MR': 'Mauritania',
    'kysion.country.name.MS': 'Montserrat',
    'kysion.country.name.MT': 'Malta',
    'kysion.country.name.MU': 'Mauritius',
    'kysion.country.name.MV': 'Maldives',
    'kysion.country.name.MW': 'Malawi',
    'kysion.country.name.MY': 'Malaysia',
    'kysion.country.name.NA': 'Namibia',
    'kysion.country.name.NC': 'New Caledonia',
    'kysion.country.name.NE': 'Niger',
    'kysion.country.name.NF': 'Norfolk Island',
    'kysion.country.name.NG': 'Nigeria',
    'kysion.country.name.NI': 'Nicaragua',
    'kysion.country.name.NL': 'Netherlands',
    'kysion.country.name.NO': 'Norway',
    'kysion.country.name.NP': 'Nepal',
    'kysion.country.name.NR': 'Nauru',
    'kysion.country.name.NU': 'Niue',
    'kysion.country.name.OM': 'Oman',
    'kysion.country.name.PA': 'Panama',
    'kysion.country.name.PG': 'Papua New Guinea',
    'kysion.country.name.PH': 'Philippines',
    'kysion.country.name.PK': 'Pakistan',
    'kysion.country.name.PM': 'Saint Pierre and Miquelon',
    'kysion.country.name.PN': 'Pitcairn Islands',
    'kysion.country.name.PR': 'Puerto Rico',
    'kysion.country.name.PS': 'Palestine',
    'kysion.country.name.PT': 'Portugal',
    'kysion.country.name.PW': 'Palau',
    'kysion.country.name.QA': 'Qatar',
    'kysion.country.name.RE': 'Réunion',
    'kysion.country.name.RO': 'Romania',
    'kysion.country.name.RU': 'Russia',
    'kysion.country.name.RW': 'Rwanda',
    'kysion.country.name.SA': 'Saudi Arabia',
    'kysion.country.name.SB': 'Solomon Islands',
    'kysion.country.name.SC': 'Seychelles',
    'kysion.country.name.SD': 'Sudan',
    'kysion.country.name.SE': 'Sweden',
    'kysion.country.name.SG': 'Singapore',
    'kysion.country.name.SH': 'Saint Helena',
    'kysion.country.name.SI': 'Slovenia',
    'kysion.country.name.SJ': 'Svalbard and Jan Mayen',
    'kysion.country.name.SK': 'Slovakia',
    'kysion.country.name.SL': 'Sierra Leone',
    'kysion.country.name.SM': 'San Marino',
    'kysion.country.name.SN': 'Senegal',
    'kysion.country.name.SO': 'Somalia',
    'kysion.country.name.SR': 'Suriname',
    'kysion.country.name.SS': 'South Sudan',
    'kysion.country.name.ST': 'São Tomé and Príncipe',
    'kysion.country.name.SV': 'El Salvador',
    'kysion.country.name.SX': 'Sint Maarten',
    'kysion.country.name.TC': 'Turks and Caicos Islands',
    'kysion.country.name.TD': 'Chad',
    'kysion.country.name.TF': 'French Southern Territories',
    'kysion.country.name.TG': 'Togo',
    'kysion.country.name.TH': 'Thailand',
    'kysion.country.name.TJ': 'Tajikistan',
    'kysion.country.name.TK': 'Tokelau',
    'kysion.country.name.TL': 'East Timor',
    'kysion.country.name.TM': 'Turkmenistan',
    'kysion.country.name.TN': 'Tunisia',
    'kysion.country.name.TO': 'Tonga',
    'kysion.country.name.TT': 'Trinidad and Tobago',
    'kysion.country.name.TV': 'Tuvalu',
    'kysion.country.name.TZ': 'Tanzania',
    'kysion.country.name.UA': 'Ukraine',
    'kysion.country.name.UG': 'Uganda',
    'kysion.country.name.UM': 'U.S. Minor Outlying Islands',
    'kysion.country.name.US': 'United States',
    'kysion.country.name.UY': 'Uruguay',
    'kysion.country.name.UZ': 'Uzbekistan',
    'kysion.country.name.VA': 'Vatican City',
    'kysion.country.name.VC': 'Saint Vincent and the Grenadines',
    'kysion.country.name.VE': 'Venezuela',
    'kysion.country.name.VG': 'British Virgin Islands',
    'kysion.country.name.VI': 'U.S. Virgin Islands',
    'kysion.country.name.VN': 'Vietnam',
    'kysion.country.name.VU': 'Vanuatu',
    'kysion.country.name.WF': 'Wallis and Futuna',
    'kysion.country.name.WS': 'Samoa',
    'kysion.country.name.YE': 'Yemen',
    'kysion.country.name.YT': 'Mayotte',
    'kysion.country.name.ZM': 'Zambia',
    'kysion.country.name.ZW': 'Zimbabwe'
  }
}
